spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:postgresql://localhost:5434/crm"
    username: myuser
    password: mypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8082
