services:
  Order-Service:
    image: postgres
    container_name: "order1_service"
    ports:
      - "5433:5432"
    environment:
       - "POSTGRES_USER=myuser"
       - "POSTGRES_PASSWORD=mypassword"
       - "POSTGRES_DB=mydatabase"
    volumes:
    - order_service_data:/var/lib/postgres/data
  Identity-Service:
    image: postgres
    container_name: "Identity-Service"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
      - identity_service_data:/var/lib/postgresql/data

  Product_Service:
    image: mongo
    container_name: "product_service"
    ports:
      - "27019:27017"
    environment:
       - "MONGO_INITDB_ROOT_USERNAME=mongouser"
       - "MONGO_INITDB_ROOT_PASSWORD=mongopassword"
       - POSTGRES_DB= mongodb
    volumes:
      - product_service_data:/var/lib/data/db
  Cart-Service:
    image: mongo
    container_name: "cart_service"
    ports:
      - "27018:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongouser"
      - "MONGO_INITDB_ROOT_PASSWORD=mongopassword"
      - POSTGRES_DB= mongodb
    volumes:
      - cart_service_data:/var/lib/data/db

  Customer-Service:
    image: mysql
    container_name: "customer-service"
    ports:
      - "3307:3306"
    environment:
    - "MYSQL_ROOT_PASSWORD=rootpassword"
    - "MYSQL_DATABASE=mydatabase"
    - "MYSQL_USER=myuser"
    - "MYSQL_PASSWORD=mypassword"
    volumes:
      - customer_service_data:/var/lib/mysql
  order-service:
    image: turkcell-order-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://Order-Service:5432/order-service"


  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
volumes:
  order_service_data:
  identity_service_data:
  product_service_data:
  cart_service_data:
  customer_service_data: