spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3307/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka" #buradada url le çal??t?royurz bir s?k?nt? olmaz çünkü servicesler gibi gbirden fazla instance ile çal??m?yorlar
    register-with-eureka: true #beni kay?t et
    fetch-registry: true #kay?tl?lar? al