spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27019/crm
      username: mongouser
      password: mongopassword
      authentication-database: admin
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka" #buradada url le çal??t?royurz bir s?k?nt? olmaz çünkü servicesler gibi gbirden fazla instance ile çal??m?yorlar
    register-with-eureka: true #beni kay?t et
    fetch-registry: true #kay?tl?lar? al